version: '3.3'
services:
  # app:
  #   container_name: gin_demo
  #   build: .
  #   ports:
  #     - ${EXPOSE_PORT}:${PORT}
  #   restart: on-failure
  #   volumes:
  #     - ./:/app/
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   environment:
  #     WAIT_HOSTS: postgres:${DB_PORT}
  #     WAIT_BEFORE_HOSTS: 30
  #     WAIT_SLEEP_INTERVAL: 6
  #   networks:
  #     - airway-cargo-network

  postgres:
    image: postgres:latest
    container_name: airway-cargo-db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5433:5432'
    networks:
      - airway-cargo-network
    # volumes:
    #   - database_postgres:/var/lib/postgresql/data

# volumes:
#   database_postgres:

networks:
  airway-cargo-network:
    driver: bridge